Added sort, pick, omit
js-tasks-ru/js-20211109_ivan-balakirev pull request #2
Opened 2021-11-14 10:27 UTC by IvanBalakirev

2021-11-14 10:28 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-11-14 17:33 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    return a.localeCompare( b, undefined, { caseFirst: 'upper' } );
при использовании `localeCompare` необходимо задать локали: вместо `undefined` используйте `['ru', 'en']`

2021-11-14 17:34 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  unicodeArr.sort( function( a, b ) {
не следует разделять массив на `latinArr` и `unicodeArr`, метод `localeCompare` умеет отличать это самостоятельно

2021-11-14 17:34 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    latinArr.reverse();
от метода `reverse` следует отказаться, нужно сразу сортировать в нужно порядке

2021-11-14 17:35 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    if ( fields.indexOf( key ) !== - 1 ) {
подумайте, может следует использовать метод `includes`?

2021-11-14 17:35 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +    if ( fields.indexOf( key ) === - 1 ) {
подумайте, может следует использовать метод `includes`?

2021-11-14 17:35 UTC, dosandk requested changes
функцию `sortStrings` следует поправить в соответствии с комментариями

2021-11-15 10:27 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-11-16 10:14 UTC, dosandk approved these changes
good 👍

2021-11-16 10:14 UTC, merged