Getters, invert, unique
js-tasks-ru/js-20211109_ivan-balakirev pull request #3
Opened 2021-11-17 17:15 UTC by IvanBalakirev

2021-11-17 17:16 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-11-18 18:56 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    const pathArr = path.split( '.' );
было бы неплохо вынести `path.split('.')` в родительскую функцию, иначе данная операция будет выполняться каждый раз при вызове геттера, хотя данное значение требуется рассчитать только один раз при создании геттера

2021-11-18 18:57 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    for ( let i = 0; i < pathArr.length; i ++ ) {
для итерации по массиву лучше использовать `for...of`, это позволит избавиться от объявления переменной для инкремента https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Statements/for...of

2021-11-18 18:58 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +  for ( let key in obj ) {
`const key`

2021-11-18 18:58 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +export function uniq( arr ) {
good 👍

2021-11-18 18:58 UTC, dosandk requested changes
решение `createGetter` следует поправить

2021-11-19 07:35 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-11-19 16:20 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +  const pathArr = path.split( '.' );
было бы неплохо вынести `path.split('.')` в родительскую функцию, иначе данная операция будет выполняться каждый раз при вызове геттера, хотя данное значение требуется рассчитать только один раз при создании геттера

2021-11-19 16:21 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +  const inverted = {};
👍 good

2021-11-19 16:21 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/3-trim-symbols/index.js
> +  const arrFromString = string.split( '' );
good 👍

2021-11-19 16:21 UTC, dosandk approved these changes
все good, только следует поправить решение `createGetter`

2021-11-19 16:22 UTC, merged