Sort table v2 + tooltip
js-tasks-ru/js-20211109_ivan-balakirev pull request #7
Opened 2021-11-29 15:49 UTC by IvanBalakirev

2021-11-29 15:50 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-11-30 17:46 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-12-01 13:40 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-12-02 11:49 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +    const $header = document.getElementsByClassName( 'sortable-table__header' )[ 0 ];
лучше использовать `querySelectorAll` или в данном случае `querySelector` чтобы не обращаться к элементу с индексом `0`.
Более того, `getElementsByClassName` возвращает коллекцию типа "HTMLCollection", которая является динамической, все изменения которые произойдут в DOM повлияют на значения в данной коллекции
А `querySelectorAll` возвращает коллекцию типа `NodeList` которая динамической не является

2021-12-02 11:50 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +      $output += this.headerConfig.map( function( data ) {
старайтесь избавляться от конкатенации шаблонов, отдавайте предпочтение методу map

2021-12-02 11:51 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +    document.addEventListener( 'pointerover', this.show.bind( this ) );
нельзя делать `bind` в тех обработчиках, которые мы планируем удалять в будущем
посмотрите пожалуйста разбор этого момента на занятии

2021-12-02 11:51 UTC, dosandk requested changes
необходимо внести правки согласно комментариев

2021-12-02 12:56 UTC, IvanBalakirev commented on 06-events-practice/1-sortable-table-v2/index.js
> +    const $header = document.getElementsByClassName( 'sortable-table__header' )[ 0 ];
Не понял как без [0] обращаться

2021-12-02 12:57 UTC, IvanBalakirev commented on 06-events-practice/1-sortable-table-v2/index.js
> +      $output += this.headerConfig.map( function( data ) {
Постараюсь, сейчас нет времени на переделку ;(

2021-12-02 13:01 UTC, IvanBalakirev commented on 06-events-practice/2-tooltip/index.js
> +    document.addEventListener( 'pointerover', this.show.bind( this ) );
Поменял на стрелочный метод

2021-12-02 13:01 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-12-02 13:04 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-12-02 13:06 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-12-02 20:48 UTC, dosandk approved these changes
👍 good

2021-12-02 20:48 UTC, merged